version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/socialnetwork  # Bind mount the code to the container
    ports:
      - "8001:8001"
    depends_on:
      - db
   
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
 

volumes:
  postgres_data:

