# Generated by Django 5.1.1 on 2024-09-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermaster",
            name="role",
            field=models.CharField(
                choices=[("Read", "Read"), ("Write", "Write"), ("Admin", "Admin")],
                default="Read",
                max_length=10,
            ),
        ),
    ]
